spring:
  ai:
    dashscope:
      api-key: sk-d07ac08eefbd4975b3b901462bfe1ce0
      chat:
        options:
          result-format: message
  datasource:
    url: jdbc:mysql://localhost:3306/nebula_ultra_db?allowMultiQueries=true
    username: root
    password: Zjw20030701
  data:
    redis:
      host: localhost
      port: 6379
      password: Zjw20030701
server:
  port: 3701
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always